### PR TITLE
drop table only on schema-change

### LINKED ISSUE #1348: Defining entities (and other constructs) without any changes renders their instances inaccessible
When redefining entities without any changes, existing instances become inaccessible. In such cases, we should be able to access previously defined instances. Moreover, in case of changes, the database can grow indefinitely, we may want to drop instances of previous entity definitions instead of simply making them inaccessible. 

Example and steps to reproduce using Fractl REPL/nREPL:

```
(component :TestModel101.Core)
=> :TestModel101.Core

(require '[fractl.component :as cn])
=> nil

(cn/switch-component :TestModel101.Core)
=> :TestModel101.Core

(entity
 :TestModel101.Core/Nice
 {:Name :String, :meta {:Order [:Name]}, :rbac nil})
=> :TestModel101.Core/Nice

{:TestModel101.Core/Nice {:Name? "Hasnain"}}
=> :not-found

{:TestModel101.Core/Nice {:Name "Hasnain"}}
=>
({:type-*-tag-*- :entity,
  :-*-type-*- [:TestModel101.Core :Nice],
  :Name "Hasnain",
  :__Id__ "0163dd14-1392-4eb4-8eb7-d4d82ec6419f"})

{:TestModel101.Core/Nice {:Name? "Hasnain"}}
=>
[{:type-*-tag-*- :entity,
  :-*-type-*- [:TestModel101.Core :Nice],
  :Name "Hasnain",
  :__Id__ "0163dd14-1392-4eb4-8eb7-d4d82ec6419f",
  :__instmeta__ nil}]

;; redefine entity without any changes
(entity
 :TestModel101.Core/Nice
 {:Name :String, :meta {:Order [:Name]}, :rbac nil})
=> :TestModel101.Core/Nice

{:TestModel101.Core/Nice {:Name? "Hasnain"}}
=> :not-found ;; here, we should get an instance defined earlier
```

### PR DESCRIPTION
**Pull request by vijayfractl**
fixes #1348

### CODE REVIEW

**Review by hasnainnaeem — APPROVED** [review]

File: src/fractl/lang/tools/repl.clj [hunk 1]
```diff
@@ -80,13 +81,37 @@
     (li/record-attributes (second exp))
     (nth exp 2)))
 
+(defn- raw-definition [exp]
```
Comment (pratik-fractl) [inline src/fractl/lang/tools/repl.clj:84]: Minor nitpick, let's rename this to `get-raw-definition`

File: src/fractl/lang/tools/repl.clj [hunk 2]
```diff
@@ -80,13 +81,37 @@
...
+                     (li/record-name spec)
+                     spec)
+          rec-attrs (if (map? spec)
+                      (li/record-attributes spec)
+                      (nth exp 2))]
+      (case (first exp)
+        entity (raw/find-entity rec-name)
+        relationship (raw/find-relationship rec-name)))))
+
+(defn- schema-changed? [exp old-def]
```
Comment (pratik-fractl) [inline src/fractl/lang/tools/repl.clj:98]: Also, let's rename this to `is-schema-changed?`

**Review by pratik-fractl — COMMENTED** [review]
Some nitpick comments.

**Review by pratik-fractl — APPROVED** [review]
